dist: bionic

language: generic

before_install:
  - curl -L https://github.com/getzola/zola/releases/download/v0.11.0/zola-v0.11.0-x86_64-unknown-linux-gnu.tar.gz > zola.tar.gz
  - tar -xzf zola.tar.gz

before_script:
  - ./zola build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  verbose: true
